# Generated by Django 5.1.6 on 2025-07-20 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fyps', '0004_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criteria', models.JSONField(help_text='List of criteria with max scores, e.g. [{"name": "Originality", "max": 10}]')),
                ('max_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(help_text='Scores per criterion, e.g. [{"name": "Originality", "score": 8}]')),
                ('total_score', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='fyps.project')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.evaluationrubric')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'evaluator')},
            },
        ),
    ]
